### ISSUE TITLE
一个账号的时候正常 多个账号会识别成一个账号

### ISSUE THREAD

**Issue by bafangseo** [Cluas/189checkin#2]
,号分隔没错啊

是什么问题呢

Run user='***'
共有 1 个账号，即将开始签到
用户名不合法
Traceback (most recent call last):
  File "checkin.py", line 146, in <module>
    helper.check_in()
  File "checkin.py", line 22, in check_in
    self.login()
  File "checkin.py", line 100, in login
    redirect_url = r.json()["toUrl"]
KeyError: 'toUrl'
Error: Process completed with exit code 1.

**Comment by Cluas** [comment]
> ,号分隔没错啊
> 
> 是什么问题呢
> 
> Run user='***'
> 共有 1 个账号，即将开始签到
> 用户名不合法
> Traceback (most recent call last):
> File "checkin.py", line 146, in
> helper.check_in()
> File "checkin.py", line 22, in check_in
> self.login()
> File "checkin.py", line 100, in login
> redirect_url = r.json()["toUrl"]
> KeyError: 'toUrl'
> Error: Process completed with exit code 1.

命令写错了 现在可以用“ ”分割账号密码，我修一下吧

**Comment by Cluas** [comment]
已经修复了， 你试试@bafangseo
